export enum OnboardingAction {
  SET_GET_STARTED = "SET_GET_STARTED",
  SET_PASSWORD = "SET_PASSWORD",
  SET_KYC = "SET_KYC",
  SET_COMPANY_NUMBER = "SET_COMPANY_NUMBER",
  SET_AUTHENTICATED = "SET_AUTHENTICATED",
  UPDATE_FILE_LIST = "UPDATE_FILE_LIST",
  SET_LOGIN_DETAILS = "SET_LOGIN_DETAILS",
}
